/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface ThreeD {
    }
}
declare global {
    interface HTMLThreeDElement extends Components.ThreeD, HTMLStencilElement {
    }
    var HTMLThreeDElement: {
        prototype: HTMLThreeDElement;
        new (): HTMLThreeDElement;
    };
    interface HTMLElementTagNameMap {
        "three-d": HTMLThreeDElement;
    }
}
declare namespace LocalJSX {
    interface ThreeD {
    }
    interface IntrinsicElements {
        "three-d": ThreeD;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "three-d": LocalJSX.ThreeD & JSXBase.HTMLAttributes<HTMLThreeDElement>;
        }
    }
}
